# Forge — DragonRuby game framework
# https://forge.game
#
# Usage:
#   require "app/forge"
#
#   class MyGame < Forge::Entity
#     script MyScript
#   end
#
#   def tick(args)
#     Forge.tick(args)
#   end

require_relative "base/process"
require_relative "base/scriptable"
require_relative "base/widgetable"
require_relative "base/script"
require_relative "base/widget"
require_relative "base/entity"
require_relative "base/user"

require_relative "utils/recyclable_pool"
require_relative "utils/cooldown"
require_relative "utils/delayer"
require_relative "utils/tweenie"
require_relative "utils/scheduler"
require_relative "utils/stat"
require_relative "utils/l_point"
require_relative "utils/scaler"
require_relative "utils/layer"
require_relative "utils/utils"
require_relative "utils/serializable"
require_relative "utils/const"
require_relative "utils/json"
require_relative "utils/http"
require_relative "utils/fs"

require_relative "phys/velocity"
require_relative "phys/velocity_array"

require_relative "ui/colors"
require_relative "ui/theme"
require_relative "ui/component"
require_relative "ui/context"
require_relative "ui/button"
require_relative "ui/label"
require_relative "ui/text_input"
require_relative "ui/checkbox"
require_relative "ui/toggle"
require_relative "ui/slider"
require_relative "ui/progress_bar"
require_relative "ui/panel"
require_relative "ui/dropdown"
require_relative "ui/radio_group"
require_relative "ui/layout"

# Game orchestration (camera, fx, optional Game class, builder DSL)
require_relative "base/camera"
require_relative "base/fx"
require_relative "base/game"
require_relative "base/builder"

require_relative "package_manager"

module Forge
  class Config
    attr_accessor :game_class, :ui_theme, :api_url, :api_key

    def initialize
      @api_url = "https://forge.game/api"
      @ui_theme = nil
      @game_class = nil
    end
  end

  # Asset maps loaded per package (populated by packages.rb)
  class << self
    attr_accessor :config, :asset_maps

    def configure(&blk)
      @config ||= Config.new
      blk.call(@config) if blk
      @config
    end

    # Per-frame entry point. Delegates to the configured game class if one is
    # set (so the orchestrator gets pre_update / update / post_update / render),
    # otherwise falls back to a plain Process update tick for empty projects.
    def tick(args)
      game_class = @config&.game_class
      if game_class
        instance = game_class.respond_to?(:s) ? game_class.s : (@game_instance ||= game_class.new)
        instance.args = args if instance.respond_to?(:args=)
        if instance.respond_to?(:tick)
          instance.tick
        else
          Process.update_all(1)
          Scheduler.tick
        end
      else
        Process.update_all(1)
        Scheduler.tick
      end

      # Advance any pending async HTTP requests every frame.
      Http.tick
    end

    # Resolve an asset path within a package.
    # @param package_name [String] package name
    # @param logical_path [String] logical path within package (e.g., "sprites/player.png")
    # @return [String, nil] resolved absolute path or nil if not found
    #
    # Usage:
    #   Forge.asset_path("ldtk_parser", "data/levels/demo.ldtk")
    #   # => "/path/to/project/packages/ldtk_parser/assets/data/levels/demo.ldtk"
    def asset_path(package_name, logical_path)
      return logical_path if logical_path.start_with?("/")
      return logical_path if logical_path.start_with?("packages/")

      maps = @asset_maps || {}
      pkg_map = maps[package_name] || {}

      # Try exact match first
      pkg_map[logical_path] ||
        pkg_map["#{logical_path}.png"] ||
        pkg_map[logical_path.sub(".png", "")]
    end

    # Get the directory path for a package.
    # @param package_name [String]
    # @return [String] path to package directory
    def package_dir(package_name)
      File.join("packages", package_name)
    end

    # Get the assets directory for a package.
    # @param package_name [String]
    # @return [String] path to package assets directory
    def package_assets_dir(package_name)
      File.join("packages", package_name, "assets")
    end

    # List all asset paths for a package.
    # @param package_name [String]
    # @return [Hash] logical_name => absolute_path mapping
    def package_assets(package_name)
      (@asset_maps || {})[package_name] || {}
    end
  end
end

# Load api_key.rb from the project root if it exists. Generated by the
# website on project download; defines `Forge::API_KEY` and `Forge::API_URL`.
# Gitignored — never commit it.
if Forge::Fs.exists?("api_key.rb")
  require "api_key"
else
  module Forge
    class << self
      def api_key
        raise "Forge API key not configured. Download a project from https://forge.game to get your API key."
      end

      def api_url
        @config&.api_url || "https://forge.game/api"
      end
    end
  end
end
