class ForgeController < ApplicationController
  skip_before_action :verify_authenticity_token
  layout "application"

  # GET /new — "New Project" page
  def new
    render layout: "application"
  end

  # GET /new/download — generates and serves the Forge base zip
  def download
    # Authenticate via API key if provided
    authenticate_by_api_key

    if logged_in?
      # Registered user: create a new API key per download (keeps keys distinct per project)
      @api_key = current_user.api_keys.create!(
        name: "Project #{Time.current.strftime('%Y-%m-%d %H:%M')}"
      )
    elsif @api_key
      # API key provided via Authorization header — use it
      # This supports re-downloading with the same key (e.g., if user loses their zip)
    else
      # Completely anonymous: create anonymous user and API key
      anonymous_user = User.find_or_create_by!(anonymous: true) do |u|
        u.username = "anonymous_#{SecureRandom.hex(4)}"
      end
      @api_key = anonymous_user.api_keys.create!(
        name: "Project #{Time.current.strftime('%Y-%m-%d %H:%M')}"
      )
    end

    # Increment download count
    @api_key.increment!(:download_count)

    # Build the zip with this API key
    zip_data = generate_forge_zip(@api_key)

    send_data zip_data, filename: "forge-project.zip", type: "application/zip", disposition: "attachment"
  end

  private

  def generate_forge_zip(api_key)
    require "zip"

    buffer = StringIO.new
    Zip::OutputStream.write_buffer(buffer) do |zip|
      core_path = Rails.root.join("core")

      Dir.glob("#{core_path}/**/*", File::FNM_DOTMATCH).each do |file_path|
        next if File.directory?(file_path)
        next if file_path =~ /\.drp$/

        # Calculate relative path within core/
        relative_path = file_path.sub("#{core_path}/", "")

        # Substitute api_key.rb.example with the real API key
        if relative_path == "api_key.rb.example"
          api_key_content = <<~RUBY
            # This file is generated when you download a project from forge.game.
            # Do not commit this file — it is automatically added to .gitignore.
            module Forge
              API_KEY = "#{api_key.key}"
              API_URL = "https://forge.game/api"
            end
          RUBY
          zip.put_next_entry("api_key.rb")
          zip.write(api_key_content)
        else
          zip.put_next_entry(relative_path)
          zip.write(File.read(file_path))
        end
      end

      # DragonRuby requires metadata/game_metadata.txt to launch a project.
      zip.put_next_entry("metadata/game_metadata.txt")
      zip.write(<<~META)
        devid=forge_user
        devtitle=Forge Developer
        gameid=my_forge_game
        gametitle=My Forge Game
        version=0.1
        icon=metadata/icon.png
        compile_ruby=false
        sprite_resolution_height=720
        sprite_resolution_width=1280
      META

      # README explaining how to use the project.
      zip.put_next_entry("README.md")
      zip.write(<<~MD)
        # My Forge Game

        Generated by [DragonRuby Forge](https://forge.game) — a fresh DragonRuby project
        pre-wired with the Forge base library and package manager.

        ## Run it

        Drag this folder onto your DragonRuby executable, or copy it into your
        DragonRuby installation and run:

            ./dragonruby my-forge-game

        ## Add packages

        Open `packages.rb` and add packages, e.g.:

            Forge.add_package("starter_kit")
            Forge.add_package("health")
            Forge.add_package("ui_components")

        Browse the registry: <https://forge.game>

        ## Customize

        - **`app/main.rb`** — your `tick` entry point. Configure your `Game` class here.
        - **`packages.rb`** — declares which packages your game uses (auto-managed).
        - **`packages/`** — installed package source (auto-managed; commit it for reproducible builds).
        - **`api_key.rb`** — your Forge API key (do **not** commit; already in `.gitignore`).

        ## Publish your own packages

        Register at <https://forge.game> to claim your API key, then in console:

            Forge.publish_package(
              name: "my-cool-script",
              version: "1.0.0",
              description: "Does something cool",
              scripts: ["MyCoolScript"],
              tags: ["gameplay"]
            )

        Happy hacking!
      MD
    end

    buffer.string
  end
end
